[project]
name = "ai-project-two-resume-critiqueer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Linaa", email = "ishimwelina06@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
ai-project-two-resume-critiqueer = "ai_project_two_resume_critiqueer:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
